CREATE TABLE `Test Template_Test` (TestID int(10) NOT NULL AUTO_INCREMENT, PRIMARY KEY (TestID)) ENGINE=InnoDB;
CREATE TABLE Test_Answer (TestID int(10) NOT NULL, AnswerID int(10) NOT NULL, PRIMARY KEY (TestID, AnswerID)) ENGINE=InnoDB;
CREATE TABLE User_Test (UserID int(10) NOT NULL, TestID int(10) NOT NULL, PRIMARY KEY (UserID, TestID)) ENGINE=InnoDB;
CREATE TABLE Course_Effect_Question (Course_EffectID int(11) NOT NULL, QuestionID int(11) NOT NULL, PRIMARY KEY (Course_EffectID, QuestionID)) ENGINE=InnoDB;
CREATE TABLE Test_Template_Test (Test_TemplateID int(11) NOT NULL, TestID int(11) NOT NULL, PRIMARY KEY (Test_TemplateID, TestID)) ENGINE=InnoDB;
CREATE TABLE University_Faculty (UniversityID int(11) NOT NULL, FacultyID int(11) NOT NULL, PRIMARY KEY (UniversityID, FacultyID)) ENGINE=InnoDB;
CREATE TABLE User_Test2 (UserID int(11) NOT NULL, TestID int(11) NOT NULL, PRIMARY KEY (UserID, TestID)) ENGINE=InnoDB;
CREATE TABLE Test_Template_Question () ENGINE=InnoDB;
CREATE TABLE Test_Answer2 (TestID int(11) NOT NULL, AnswerID int(11) NOT NULL, PRIMARY KEY (TestID, AnswerID)) ENGINE=InnoDB;
CREATE TABLE `User` (ID int(11) NOT NULL AUTO_INCREMENT, FacultyID int(11), StudentNumber varchar(255), Email varchar(255), Name varchar(255), Surname varchar(255), Password varchar(255), Phone varchar(255), Adress varchar(255), Date_created date, Age int(11), Discriminator varchar(255) NOT NULL, PRIMARY KEY (ID)) ENGINE=InnoDB;
CREATE TABLE Faculty (ID int(11) NOT NULL AUTO_INCREMENT, UniversityID int(11), Name varchar(255), PRIMARY KEY (ID)) ENGINE=InnoDB;
CREATE TABLE Faculty_Effect (ID int(11) NOT NULL AUTO_INCREMENT, FacultyID int(11), Description varchar(255), Text varchar(255), PRIMARY KEY (ID)) ENGINE=InnoDB;
CREATE TABLE Course (ID int(11) NOT NULL AUTO_INCREMENT, UserID int(11) NOT NULL, FacultyID int(11), ECTS int(11) NOT NULL, Name varchar(255), PRIMARY KEY (ID)) ENGINE=InnoDB;
CREATE TABLE Course_Effect (ID int(11) NOT NULL AUTO_INCREMENT, Faculty_EffectID int(11), CourseID int(11), Description varchar(255), Text varchar(255), PRIMARY KEY (ID)) ENGINE=InnoDB;
CREATE TABLE Question (ID int(11) NOT NULL AUTO_INCREMENT, Test_TemplateID int(11) NOT NULL, Points double NOT NULL, Text varchar(255), Subevaluation_criteria varchar(255), Answer_lenght int(11), Right_question int(11), Discriminator varchar(255) NOT NULL, PRIMARY KEY (ID)) ENGINE=InnoDB;
CREATE TABLE Choise (ID int(11) NOT NULL AUTO_INCREMENT, QuestionID int(11), Text varchar(255), PRIMARY KEY (ID)) ENGINE=InnoDB;
CREATE TABLE Answer (ID int(11) NOT NULL AUTO_INCREMENT, QuestionID int(11), Score double NOT NULL, Text varchar(255), PRIMARY KEY (ID)) ENGINE=InnoDB;
CREATE TABLE Test_Template (ID int(11) NOT NULL AUTO_INCREMENT, CourseID int(11), UserID int(11), Time double NOT NULL, Evaluation_criteria varchar(255), Name varchar(255), PRIMARY KEY (ID)) ENGINE=InnoDB;
CREATE TABLE Test (ID int(11) NOT NULL AUTO_INCREMENT, Score double NOT NULL, PRIMARY KEY (ID)) ENGINE=InnoDB;
CREATE TABLE University (ID int(11) NOT NULL AUTO_INCREMENT, Name varchar(255), PRIMARY KEY (ID)) ENGINE=InnoDB;
CREATE TABLE Course_Effect_Question2 (Course_EffectID int(11) NOT NULL, QuestionID int(11) NOT NULL, PRIMARY KEY (Course_EffectID, QuestionID)) ENGINE=InnoDB;
CREATE TABLE Test_Template_Test2 (Test_TemplateID int(11) NOT NULL, TestID int(11) NOT NULL, PRIMARY KEY (Test_TemplateID, TestID)) ENGINE=InnoDB;
CREATE TABLE User_Test3 (UserID int(11) NOT NULL, TestID int(11) NOT NULL, PRIMARY KEY (UserID, TestID)) ENGINE=InnoDB;
CREATE TABLE Test_Answer3 (TestID int(11) NOT NULL, AnswerID int(11) NOT NULL, PRIMARY KEY (TestID, AnswerID)) ENGINE=InnoDB;
ALTER TABLE `User` ADD INDEX FKUser40743 (FacultyID), ADD CONSTRAINT FKUser40743 FOREIGN KEY (FacultyID) REFERENCES Faculty (ID);
ALTER TABLE Faculty_Effect ADD INDEX FKFaculty_Ef920376 (FacultyID), ADD CONSTRAINT FKFaculty_Ef920376 FOREIGN KEY (FacultyID) REFERENCES Faculty (ID);
ALTER TABLE Course ADD INDEX FKCourse312106 (FacultyID), ADD CONSTRAINT FKCourse312106 FOREIGN KEY (FacultyID) REFERENCES Faculty (ID);
ALTER TABLE Course_Effect ADD INDEX FKCourse_Eff311937 (CourseID), ADD CONSTRAINT FKCourse_Eff311937 FOREIGN KEY (CourseID) REFERENCES Course (ID);
ALTER TABLE Course_Effect ADD INDEX FKCourse_Eff604634 (Faculty_EffectID), ADD CONSTRAINT FKCourse_Eff604634 FOREIGN KEY (Faculty_EffectID) REFERENCES Faculty_Effect (ID);
ALTER TABLE Course_Effect_Question2 ADD INDEX FKCourse_Eff172352 (Course_EffectID), ADD CONSTRAINT FKCourse_Eff172352 FOREIGN KEY (Course_EffectID) REFERENCES Course_Effect (ID);
ALTER TABLE Course_Effect_Question2 ADD INDEX FKCourse_Eff131945 (QuestionID), ADD CONSTRAINT FKCourse_Eff131945 FOREIGN KEY (QuestionID) REFERENCES Question (ID);
ALTER TABLE Choise ADD INDEX FKChoise821484 (QuestionID), ADD CONSTRAINT FKChoise821484 FOREIGN KEY (QuestionID) REFERENCES Question (ID);
ALTER TABLE Answer ADD INDEX FKAnswer406515 (QuestionID), ADD CONSTRAINT FKAnswer406515 FOREIGN KEY (QuestionID) REFERENCES Question (ID);
ALTER TABLE Test_Template ADD INDEX FKTest_Templ765790 (UserID), ADD CONSTRAINT FKTest_Templ765790 FOREIGN KEY (UserID) REFERENCES `User` (ID);
ALTER TABLE Test_Template ADD INDEX FKTest_Templ864517 (CourseID), ADD CONSTRAINT FKTest_Templ864517 FOREIGN KEY (CourseID) REFERENCES Course (ID);
ALTER TABLE Test_Template_Test2 ADD INDEX FKTest_Templ783911 (Test_TemplateID), ADD CONSTRAINT FKTest_Templ783911 FOREIGN KEY (Test_TemplateID) REFERENCES Test_Template (ID);
ALTER TABLE Test_Template_Test2 ADD INDEX FKTest_Templ656768 (TestID), ADD CONSTRAINT FKTest_Templ656768 FOREIGN KEY (TestID) REFERENCES Test (ID);
ALTER TABLE Faculty ADD INDEX FKFaculty543242 (UniversityID), ADD CONSTRAINT FKFaculty543242 FOREIGN KEY (UniversityID) REFERENCES University (ID);
ALTER TABLE User_Test3 ADD INDEX FKUser_Test3271976 (UserID), ADD CONSTRAINT FKUser_Test3271976 FOREIGN KEY (UserID) REFERENCES `User` (ID);
ALTER TABLE User_Test3 ADD INDEX FKUser_Test3517315 (TestID), ADD CONSTRAINT FKUser_Test3517315 FOREIGN KEY (TestID) REFERENCES Test (ID);
ALTER TABLE Test_Answer3 ADD INDEX FKTest_Answe171918 (TestID), ADD CONSTRAINT FKTest_Answe171918 FOREIGN KEY (TestID) REFERENCES Test (ID);
ALTER TABLE Test_Answer3 ADD INDEX FKTest_Answe641155 (AnswerID), ADD CONSTRAINT FKTest_Answe641155 FOREIGN KEY (AnswerID) REFERENCES Answer (ID);
ALTER TABLE Course ADD INDEX FKCourse747545 (UserID), ADD CONSTRAINT FKCourse747545 FOREIGN KEY (UserID) REFERENCES `User` (ID);
ALTER TABLE Question ADD INDEX FKQuestion485891 (Test_TemplateID), ADD CONSTRAINT FKQuestion485891 FOREIGN KEY (Test_TemplateID) REFERENCES Test_Template (ID);
